-- System notifications: one row per recipient. Rows are snapshots and never change except `read_time`.
-- `id` is a UUIDv7 generated by the sender and doubles as the idempotency key.
CREATE TABLE notifications
(
    id                UUID PRIMARY KEY NOT NULL,
    recipient_uid     BIGINT           NOT NULL,
    notification_type TEXT             NOT NULL, -- e.g. 'governance.report_resolved'
    title             TEXT             NOT NULL,
    body              TEXT             NOT NULL,
    content_intent    JSONB,                     -- { "action": "...", "data": { ... } }
    read_time         TIMESTAMPTZ,
    create_time       TIMESTAMPTZ      NOT NULL  -- When the business event happened
);

CREATE INDEX idx_notifications_recipient_id ON notifications (recipient_uid, id DESC);
CREATE INDEX idx_notifications_recipient_unread ON notifications (recipient_uid) WHERE read_time IS NULL;
CREATE INDEX idx_notifications_create_time ON notifications (create_time);
