services:
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - '7700:7700'
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: hachimi-world
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:7700/health']
      interval: 3s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 3s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'PING']
      interval: 3s
      timeout: 5s
      retries: 3
    restart: unless-stopped
volumes:
  db-data:
  redis-data:
  meilisearch-data: