use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::PgExecutor;
use uuid::Uuid;

macro_rules! query_notifications {
    ($extra:literal $(, $arg:expr)* $(,)?) => {
        sqlx::query_as!(
            Notification, r#"
            SELECT
                id,
                recipient_uid,
                notification_type,
                title,
                body,
                content_intent,
                read_time,
                create_time
            FROM notifications
            "# + $extra,
            $($arg),*
        )
    };
}

/// @since 261005
#[derive(sqlx::FromRow)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Notification {
    /// UUIDv7 generated by the sender, also the idempotency key.
    pub id: Uuid,
    pub recipient_uid: i64,
    pub notification_type: String,
    pub title: String,
    pub body: String,
    /// `{ "action": "...", "data": { ... } }`
    pub content_intent: Option<Value>,
    pub read_time: Option<DateTime<Utc>>,
    /// When the business event happened.
    pub create_time: DateTime<Utc>,
}

pub struct NotificationDao;

impl NotificationDao {
    pub async fn insert<'e>(executor: impl PgExecutor<'e>, value: &Notification) -> sqlx::Result<()> {
        sqlx::query!("INSERT INTO notifications(
                id,
                recipient_uid,
                notification_type,
                title,
                body,
                content_intent,
                read_time,
                create_time
            ) VALUES($1, $2, $3, $4, $5, $6, $7, $8)",
            value.id,
            value.recipient_uid,
            value.notification_type,
            value.title,
            value.body,
            value.content_intent,
            value.read_time,
            value.create_time
        ).execute(executor).await?;
        Ok(())
    }

    pub async fn get_by_id<'e>(executor: impl PgExecutor<'e>, id: Uuid) -> sqlx::Result<Option<Notification>> {
        query_notifications!("WHERE id = $1", id)
            .fetch_optional(executor)
            .await
    }

    pub async fn get_by_recipient<'e>(
        executor: impl PgExecutor<'e>,
        recipient_uid: i64,
        id: Uuid,
    ) -> sqlx::Result<Option<Notification>> {
        query_notifications!("WHERE id = $1 AND recipient_uid = $2", id, recipient_uid)
            .fetch_optional(executor)
            .await
    }

    /// Created at or after `since`, newest first by id. `before_id` excludes it and anything newer.
    pub async fn list_by_recipient<'e>(
        executor: impl PgExecutor<'e>,
        recipient_uid: i64,
        before_id: Option<Uuid>,
        since: DateTime<Utc>,
        limit: i64,
    ) -> sqlx::Result<Vec<Notification>> {
        query_notifications!(
            "WHERE recipient_uid = $1
                AND ($2::uuid IS NULL OR id < $2)
                AND create_time >= $3
            ORDER BY id DESC
            LIMIT $4",
            recipient_uid, before_id, since, limit
        ).fetch_all(executor).await
    }

    /// Unread ones created at or after `since`.
    pub async fn count_unread_by_recipient<'e>(
        executor: impl PgExecutor<'e>,
        recipient_uid: i64,
        since: DateTime<Utc>,
    ) -> sqlx::Result<i64> {
        sqlx::query!(
            "SELECT COUNT(*) FROM notifications
            WHERE recipient_uid = $1 AND read_time IS NULL AND create_time >= $2",
            recipient_uid, since
        ).fetch_one(executor).await.map(|x| x.count.unwrap_or(0))
    }

    /// Only updates it if still unread, so a concurrent read time isn't overwritten. Returns
    /// whether it was updated.
    pub async fn set_read_time_if_unread<'e>(
        executor: impl PgExecutor<'e>,
        recipient_uid: i64,
        id: Uuid,
        read_time: DateTime<Utc>,
    ) -> sqlx::Result<bool> {
        sqlx::query!(
            "UPDATE notifications SET read_time = $3
            WHERE id = $1 AND recipient_uid = $2 AND read_time IS NULL",
            id, recipient_uid, read_time
        ).execute(executor).await.map(|x| x.rows_affected() > 0)
    }

    /// Sets the read time of every unread one created at or after `since`. Returns how many were
    /// updated.
    pub async fn set_read_time_all_unread<'e>(
        executor: impl PgExecutor<'e>,
        recipient_uid: i64,
        since: DateTime<Utc>,
        read_time: DateTime<Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query!(
            "UPDATE notifications SET read_time = $3
            WHERE recipient_uid = $1 AND read_time IS NULL AND create_time >= $2",
            recipient_uid, since, read_time
        ).execute(executor).await.map(|x| x.rows_affected())
    }

    /// Deletes up to `limit` notifications created before `before`, oldest first. Returns how many
    /// were deleted.
    pub async fn delete_created_before<'e>(
        executor: impl PgExecutor<'e>,
        before: DateTime<Utc>,
        limit: i64,
    ) -> sqlx::Result<u64> {
        sqlx::query!(
            "DELETE FROM notifications WHERE id IN (
                SELECT id FROM notifications
                WHERE create_time < $1
                ORDER BY create_time
                LIMIT $2
            )",
            before, limit
        ).execute(executor).await.map(|x| x.rows_affected())
    }
}
