when:
  branch:
    - master
  event:
    - push
    - manual
steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo:
        from_secret: registry_repo
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      dockerfile: Dockerfile
      registry:
        from_secret: registry_server
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      auto_tag: false
    privileged: true
  - name: deploy-production
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_ssh_host
      port:
        from_secret: deploy_ssh_port
      username:
        from_secret: deploy_ssh_username
      key:
        from_secret: deploy_ssh_key
      command_timeout: 2m
      script_stop: true
      script:
        - ./deploy_hachimi_world_server.sh