when:
  branch:
    exclude:
      - master
  event:
    - push
    - manual
steps:
  - name: build
    image: rust:1.96.0
    environment:
      SQLX_OFFLINE: true
    commands:
      - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - cargo nextest run --tests