//! The kinds of user-generated content that can be reported, and what a decision can do to each.
//!
//! The report flow is the same for every kind; the steps that touch the content are left to the
//! kind's adapter (`song.rs`, `playlist.rs`, `user.rs`): what the target looks like, which content
//! actions it offers and how to take them, what to refresh afterwards, and what to tell its owner.
//! An adapter knows its own content and nothing else, and declares its own actions.
//!
//! Each adapter implements [UgcAdapter], and each [UgcKind] variant carries its adapter; the
//! forwarding from the enum to the adapters is generated by `enum_dispatch`, so nothing here
//! matches on the kind by hand. Adding a kind means a new adapter, a variant for it and an entry
//! in [UgcKind::ALL]; the compiler points at any method the adapter leaves out.

mod playlist;
mod song;
mod user;

use crate::service::notification::ContentIntent;
use crate::web::state::AppState;
use enum_dispatch::enum_dispatch;
use serde::{Deserialize, Serialize};
use sqlx::{PgPool, PgTransaction};

/// A reportable kind. Each variant carries the kind's adapter, and [enum_dispatch] implements
/// [UgcAdapter] for the enum by forwarding to it, so calling a method on a kind runs that kind's
/// adapter without a hand-written match.
#[enum_dispatch(UgcAdapter)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UgcKind {
    Song(song::SongAdapter),
    Playlist(playlist::PlaylistAdapter),
    User(user::UserAdapter),
}

/// A target in the shape the report flow needs, whatever its kind: shown in the report queue,
/// used to check who may report it, and kept as a snapshot with each action.
/// @since 261008
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UgcTarget {
    pub owner_uid: i64,
    /// Song title, playlist name or username.
    pub title: String,
    /// Song cover, playlist cover or avatar.
    pub cover_url: Option<String>,
    /// Song display id such as `JM-ABCD-123`; empty for other kinds.
    pub display_id: String,
    /// Whether people other than the owner can see it.
    pub is_public: bool,
    /// Hidden by the platform.
    /// @since 261008
    #[serde(default)]
    pub is_hidden: bool,
}

/// Something a decision can do to the content, declared by the kind's adapter. The report flow
/// only knows its id and whether it is a penalty.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ContentAction {
    /// Stable id used in the API and stored with the decision, such as `hide`.
    pub id: &'static str,
    /// Acts against the content: it goes with an upheld report, and the owner must be told why.
    /// Otherwise it undoes an earlier penalty and goes with a rejected one.
    pub penalty: bool,
}

/// What to tell the owner about a decision on their content.
pub struct OwnerMessage {
    pub notification_type: &'static str,
    pub title: &'static str,
    pub body: String,
    pub intent: ContentIntent,
}

/// What every reportable kind provides. Implemented once per kind, in its own file; a kind that
/// leaves a method out doesn't compile.
// Only called through the concrete UgcKind, so the futures' auto traits (Send) are known
#[allow(async_fn_in_trait)]
#[enum_dispatch]
pub trait UgcAdapter {
    /// The kind's name in the API and in storage, such as `song`.
    fn name(&self) -> &'static str;

    /// Every content action the kind declares, for reading past decisions.
    fn actions(&self) -> &'static [ContentAction];

    /// Reads the target from its own table and describes it as a [UgcTarget]. None if it doesn't
    /// exist.
    async fn load(&self, pool: &PgPool, id: i64) -> sqlx::Result<Option<UgcTarget>>;

    /// Content actions a decision can take on `target` now.
    fn content_actions(&self, target: &UgcTarget) -> Vec<ContentAction>;

    /// Takes `actions`, already checked against [Self::content_actions], in the decision's
    /// transaction.
    async fn apply(&self, tx: &mut PgTransaction<'_>, id: i64, actions: &[ContentAction]) -> anyhow::Result<()>;

    /// Refreshes caches and the search index after a decision that took content actions commits.
    /// Failures are logged.
    async fn refresh(&self, state: &AppState, id: i64);

    /// How the target is named in user-facing text, such as 作品《X》, or just 作品 if it's gone.
    fn mention(&self, title: Option<&str>) -> String;

    /// Tells the owner what `actions` did to their content. None if they did nothing.
    /// `reason_suffix` is appended to the body as is.
    fn owner_message(&self, id: i64, target: &UgcTarget, actions: &[ContentAction], reason_suffix: &str) -> Option<OwnerMessage>;
}

impl UgcKind {
    /// Every kind, so names can be parsed back. Add new kinds here too.
    pub const ALL: [UgcKind; 3] = [
        Self::Song(song::SongAdapter),
        Self::Playlist(playlist::PlaylistAdapter),
        Self::User(user::UserAdapter),
    ];

    pub fn parse(s: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|x| x.name() == s)
    }

    pub fn as_str(self) -> &'static str {
        self.name()
    }
}

#[cfg(test)]
mod tests {
    use super::UgcKind;

    #[test]
    fn every_kind_parses_back() {
        for kind in UgcKind::ALL {
            assert_eq!(UgcKind::parse(kind.as_str()), Some(kind));
        }
    }
}
